blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/danielphilipjohnson/eslint-plugin-tailwind-organizer/discussions
    about: Use Discussions for help or general questions.
